name: wms
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_size_and_fade: ^3.0.1
  auto_route: ^7.8.0
  capped_progress_indicator: ^0.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.8
  json_annotation: ^4.8.1
  riverpod: ^2.3.7
  shared_preferences: ^2.2.2

  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  data_table_2: ^2.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  custom_lint: ^0.5.2
  riverpod_lint: ^2.2.0
  auto_route_generator: ^7.3.1
  flutter_gen_runner: ^5.3.1
  mocktail: ^1.0.0
  script_runner: ^0.3.1

  drift_dev: ^2.13.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/png/
    - assets/images/svg/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
